[images]
  remote_images = [
    "https://ext.same-assets.com/3595534517/*.jpeg",
    "https://ext.same-assets.com/3595534517/*.png",
    "https://ext.same-assets.com/3595534517/*.svg",
    "https://ext.same-assets.com/1141740297/*.svg",
    "https://ext.same-assets.com/1141740297/*.bin"
  ]

[build]
  command = "bun run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NEXT_USE_NETLIFY_EDGE = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"
